### ISSUE TITLE
application which built with native-image startups error caused by micrometer

### ISSUE THREAD

**Issue by szhaoyu** [micronaut-projects/micronaut-micrometer#194]
### Steps to Reproduce

1. mn create-app -f micrometer-prometheus -b maven
2. mvn clean package
3. native-image com.xxx.Appliction -cp target/xxx**.jar
4. ./xxx startup

### Expected Behaviour
native application startup success

### Actual Behaviour
fail with error.
15:36:44.541 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type [javax.sql.DataSource]: Class must be instance of com.codahale.metrics.MetricRegistry or io.micrometer.core.instrument.MeterRegistry
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type [javax.sql.DataSource]: Class must be instance of com.codahale.metrics.MetricRegistry or io.micrometer.core.instrument.MeterRegistry
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2780)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at com.metabyte.ieye.Application.main(Application.java:16)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [javax.sql.DataSource]: Class must be instance of com.codahale.metrics.MetricRegistry or io.micrometer.core.instrument.MeterRegistry
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2647)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2633)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2172)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 8 common frames omitted

### Environment Information

- **Operating System**: Mac OS 11
- **Micronaut Version:** 2.1.3
- **JDK Version:** Graalvm 11

**Comment by graemerocher** [comment]
Please upgrade to 2.2.1 to resolve this issue

**Comment by szhaoyu** [comment]
Yes, it worked. Thanks.
