### ISSUE TITLE
ByteBufAllocatorMetricsBinder is causing exceptions

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-micrometer#281]
### Expected Behavior

Proper metrics.

### Actual Behaviour

```
micronaut:
  application:
    name: Test
  metrics:
    enabled: ${prop.micronaut.metrics.enabled}
    binders:
      web:
        enabled: true
      netty:
        enabled: true
        queues:
          enabled: false
        channels:
          enabled: false
        bytebuf-allocators:
          enabled: true
```

```
00:22:46.964 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.configuration.metrics.binder.netty.ByteBufAllocatorMetricsBinder] could not be loaded: Error instantiating bean of type [io.micronaut.configuration.metrics.binder.netty.ByteBufAllocatorMetricsBinder]: Collector already registered that provides name: netty_alloc_arena_allocation_count
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.micronaut.configuration.metrics.binder.netty.ByteBufAllocatorMetricsBinder] could not be loaded: Error instantiating bean of type [io.micronaut.configuration.metrics.binder.netty.ByteBufAllocatorMetricsBinder]: Collector already registered that provides name: **netty_alloc_arena_allocation_count**
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1568)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:234)

```
when enabled byte-buffers it is causing exception.

### Version

3.4.0

**Comment by graemerocher** [comment]
@n0tl3ss please take a look

**Comment by n0tl3ss** [comment]
Hi @cemo I cannot reproduce by creating the demo micronaut app and adding metrics with configuration that you provided. Can you provide me a demo project please? Thanks
