### ISSUE TITLE
java.lang.NoSuchFieldException: producerIndex in native-image

### ISSUE THREAD

**Issue by arenick001** [micronaut-projects/micronaut-micrometer#750]
### Expected Behavior

It should run without any exception

### Actual Behaviour

[main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micrometer.core.instrument.composite.CompositeMeterRegistry]

Path Taken: MeterRegistryFactory.compositeMeterRegistry(List registries,List configurers) --> MeterRegistryFactory.compositeMeterRegistry([List registries],List configurers)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micrometer.core.instrument.composite.CompositeMeterRegistry]

Path Taken: MeterRegistryFactory.compositeMeterRegistry(List registries,List configurers) --> MeterRegistryFactory.compositeMeterRegistry([List registries],List configurers)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2001)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:292)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3382)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3737)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:361)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:200)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
        at org.remotefpga.nativenode.NativeApplication.main(NativeApplication.java:15)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micrometer.core.instrument.composite.CompositeMeterRegistry]

Path Taken: MeterRegistryFactory.compositeMeterRegistry(List registries,List configurers) --> MeterRegistryFactory.compositeMeterRegistry([List registries],List configurers)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2345)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2951)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3566)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3514)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3484)
        at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1451)
        at io.micronaut.context.AbstractBeanResolutionContext.getBeansOfType(AbstractBeanResolutionContext.java:95)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBeansOfType(AbstractInitializableBeanDefinition.java:2253)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractInitializableBeanDefinition.java:1476)
        at io.micronaut.configuration.metrics.micrometer.$MeterRegistryFactory$CompositeMeterRegistry0$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2977)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2751)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1750)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:856)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:848)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.getMeterRegistry(DatasourceFactory.java:88)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.addMeterRegistry(DatasourceFactory.java:74)
        at io.micronaut.configuration.jdbc.hikari.DatasourceFactory.dataSource(DatasourceFactory.java:67)
        at io.micronaut.configuration.jdbc.hikari.$DatasourceFactory$DataSource0$Definition.instantiate(Unknown Source)
        at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:159)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2300)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2312)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3114)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext.initializeEagerBean(DefaultBeanContext.java:2688)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1995)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528)
        at io.micrometer.shaded.io.netty.util.internal.PlatformDependent$Mpsc.newMpscQueue(PlatformDependent.java:1027)
        at io.micrometer.shaded.io.netty.util.internal.PlatformDependent.newMpscQueue(PlatformDependent.java:1038)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:283)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:154)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)
        at io.micrometer.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.micrometer.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
        at io.micrometer.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
        at io.micrometer.shaded.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
        at io.micrometer.shaded.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)
        at io.micrometer.shaded.reactor.netty.resources.DefaultLoopResources.cacheNioServerLoops(DefaultLoopResources.java:213)
        at io.micrometer.shaded.reactor.netty.resources.DefaultLoopResources.cacheNioClientLoops(DefaultLoopResources.java:179)
        at io.micrometer.shaded.reactor.netty.resources.DefaultLoopResources.onClient(DefaultLoopResources.java:147)
        at io.micrometer.shaded.reactor.netty.transport.NameResolverProvider.newNameResolverGroup(NameResolverProvider.java:535)
        at io.micrometer.shaded.reactor.netty.udp.UdpResources.getOrCreateDefaultResolver(UdpResources.java:242)
        at io.micrometer.shaded.reactor.netty.udp.UdpClientConfig.defaultAddressResolverGroup(UdpClientConfig.java:105)
        at io.micrometer.shaded.reactor.netty.transport.ClientTransportConfig.resolverInternal(ClientTransportConfig.java:228)
        at io.micrometer.shaded.reactor.netty.transport.ClientTransport.connect(ClientTransport.java:59)
        at io.micrometer.shaded.reactor.netty.udp.UdpClient.connect(UdpClient.java:87)
        at io.micrometer.statsd.StatsdMeterRegistry.lambda$connectAndSubscribe$14(StatsdMeterRegistry.java:289)
        at io.micrometer.shaded.reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
        at io.micrometer.shaded.reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
        at io.micrometer.shaded.reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
        at io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Mono.java:4480)
        at io.micrometer.shaded.reactor.core.publisher.Mono.subscribeWith(Mono.java:4561)
        at io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Mono.java:4462)
        at io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Mono.java:4398)
        at io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Mono.java:4345)
        at io.micrometer.statsd.StatsdMeterRegistry.retryReplaceClient(StatsdMeterRegistry.java:297)
        at io.micrometer.statsd.StatsdMeterRegistry.connectAndSubscribe(StatsdMeterRegistry.java:287)
        at io.micrometer.statsd.StatsdMeterRegistry.prepareUdpClient(StatsdMeterRegistry.java:258)
        at io.micrometer.statsd.StatsdMeterRegistry.start(StatsdMeterRegistry.java:231)
        at io.micrometer.statsd.StatsdMeterRegistry.<init>(StatsdMeterRegistry.java:156)
        at io.micrometer.statsd.StatsdMeterRegistry.<init>(StatsdMeterRegistry.java:120)
        at io.micrometer.statsd.StatsdMeterRegistry.<init>(StatsdMeterRegistry.java:108)
        at io.micronaut.configuration.metrics.micrometer.statsd.StatsdMeterRegistryFactory.statsdMeterRegistry(StatsdMeterRegistryFactory.java:53)
        at io.micronaut.configuration.metrics.micrometer.statsd.$StatsdMeterRegistryFactory$StatsdMeterRegistry0$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2330)
        ... 46 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
        at io.micrometer.shaded.io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111)
        at io.micrometer.shaded.io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields.<clinit>(BaseMpscLinkedArrayQueue.java:55)
        ... 94 more
Caused by: java.lang.NoSuchFieldException: producerIndex
        at java.base@17.0.6/java.lang.Class.getDeclaredField(DynamicHub.java:961)
        at io.micrometer.shaded.io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107)
        ... 95 more

### Steps To Reproduce

Just add micronaut-micrometer and run the application via native-image(in JVM all the things go well)

### Environment Information

**OS:** win11
**JDK:** 
- openjdk version "17.0.6" 2023-01-17
- OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
- OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Version

4.4.6

**Comment by arenick001** [comment]
PLZ help me!

**Comment by arenick001** [comment]
this issue was solved with https://github.com/micrometer-metrics/micrometer/issues/3212.
